version: '2'
services:
    coa-app:
        image: coa
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://coa-postgresql:5432/coa
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    coa-postgresql:
        extends:
            file: postgresql.yml
            service: coa-postgresql
